### PR TITLE
optimasi dockerfile & docker-compose

### PR DESCRIPTION
**Pull request by jams008**
I optimized the base image which was smaller before, up to 1GB, now it is only 300 MB, I tidy up the writing structure and I update the docker-compose file to build automatically when it's up.

### CODE REVIEW

**Comment by ashokponkumar** [comment]
Thanks @jams008 . Can we possibly use a multistage build process? We can possibly look at https://github.com/konveyor/mig-ui/blob/master/Dockerfile for an example, and use a very similar flow.

**Comment by jams008** [comment]
okay, I'll fix it later

**Comment by ashokponkumar** [comment]
Do the following, `git commit --amend --signoff` and then `git push --force`

**Comment by jams008** [comment]
no I just use 'git commit -s -m'

**Comment by ashokponkumar** [comment]
Can you try git commit --amend --signoff and then git push --force

**Comment by jams008** [comment]
okey, i try  `git commit --amend --signoff`

**Comment by jams008** [comment]
hi @ashokponkumar , i am cannot commit using `git commit --amend --signoff`
image

**Comment by ashokponkumar** [comment]
Please remove the message in the end

**Comment by jams008** [comment]
okey, i using 'git commit --amend --signoff` only?

**Comment by jams008** [comment]
I have tried it and the ci DCO is still problematic.
image

**Comment by ashokponkumar** [comment]
Thanks for the PR @jams008 . If you are interested, feel free to make more enhancements and create new PRs.

**Comment by jams008** [comment]
hi @ashokponkumar , you're welcome.

**Pull request merged**
